### ISSUE TITLE
US3 Make organizer registration

### ISSUE THREAD

**Issue by ssheloors** [ssheloors/festivo#1]
As an organizer I want to be able to register So that I can log in and see all my events

**Comment by dotellie** [comment]
This requires using some [auth functions from the Payload REST API](https://payloadcms.com/docs/rest-api/overview#auth-operations). These are **not** exposed in the payload-rest-client so they need to be called manually. Later, for login, the authentication token needs to be persisted somehow.

**Comment by dotellie** [comment]
Fixed in #9
