### ISSUE TITLE
Proper message when the login is incorrect

### ISSUE THREAD

**Issue by ssheloors** [ssheloors/festivo#35]
Right now the app crashes when you try to login with an invalid account, this should be displayed to the user in a better way 
<details>
<summary>Error pictures</summary>

![image](https://github.com/user-attachments/assets/120f09a2-3bc1-40ce-b42f-84883ec29c79) ![image](https://github.com/user-attachments/assets/37401322-9f5d-4697-aff4-452829460a63)

</details>

### Optional changes for improving UX in my opinion
- When you haven't inputted the fields in the correct format (having the @ and minimum characters for the password) you can't click the button but its not really clear what your error is (in my opinion) would be nice to have some message or maybe even a place holder with example output would make it better!

**Comment by dotellie** [comment]
Closed with #39
